// .ci/jobs.groovy — Job DSL seed script
//
// Generates one "Pipeline" job per microservice, each pointed at its own
// services/<svc>/Jenkinsfile on the main branch. Run this from a single SEED job
// (see .ci/README-seed.md) — it creates/updates all 6 jobs in one shot.
//
// Re-run it any time: it reconciles the jobs to match this script (add a service →
// add it to the list below → re-run the seed job → the new job appears).

// ---- configuration ----
def repo        = 'https://github.com/cloudwithabhoy/new_project.git'
def gitCredsId  = 'git-cred'     // Jenkins credential ID for cloning the repo
def gitBranch   = '*/main'

def services = [
    'api-gateway',
    'auth',
    'catalog',
    'order',
    'inventory',
    'frontend',
]

// ---- generate one pipeline job per service ----
services.each { svc ->
    pipelineJob(svc) {
        description("CI for the ${svc} microservice — lint, test, build & push image to ECR. " +
                    "Deploy stays manual. Generated by .ci/jobs.groovy (do not edit by hand).")

        // keep the last 20 builds only
        logRotator {
            numToKeep(20)
        }

        // build on a GitHub push (needs the GitHub webhook -> /github-webhook/).
        // The Jenkinsfile's `when { changeset "services/<svc>/**" }` makes unaffected
        // services a fast no-op, so one push only really builds what changed.
        triggers {
            githubPush()
        }

        definition {
            cpsScm {
                // only fetch the Jenkinsfile to LOAD the pipeline; the pipeline itself
                // does a full `checkout scm` for the build.
                lightweight(true)
                scm {
                    git {
                        remote {
                            url(repo)
                            credentials(gitCredsId)
                        }
                        branch(gitBranch)
                    }
                }
                scriptPath("services/${svc}/Jenkinsfile")
            }
        }
    }
}

println "Seed complete: generated ${services.size()} pipeline jobs -> ${services.join(', ')}"
